// ============================================================
// registry.js — Full building roster
// Three ages: Settlement → Town → Castle
// ============================================================

// Tier gates (checked in placement.js):
//   tier:2  requires a completed 'settlement_hall' + 'forge'
//   tier:3  requires a completed 'town_hall' + 'mint'
//   tier:'special' — no gate, placed by game logic only

export const BUILDINGS = {

  // ── Special ──────────────────────────────────────────────
  capital: {
    name: 'Capital',
    tier: 'special',
    w: 4, h: 4,
    buildTime: 0,
    hp: 1000,
    staffSlots: 0,
    description: 'Your permanent seat of power. Placed at game start, cannot be destroyed. Spawns your first citizens.',
  },

  // ── Tier 1 — The Settlement ───────────────────────────────
  settlement_hall: {
    name: 'Settlement Hall',
    tier: 1,
    w: 3, h: 3,
    buildTime: 60,
    hp: 200,
    staffSlots: 0,
    description: 'The heart of a new community. Spawns 3 citizens when completed. Required before building a Town Hall.',
  },
  log_cabin: {
    name: 'Log Cabin',
    tier: 1,
    w: 2, h: 2,
    buildTime: 30,
    hp: 80,
    staffSlots: 0,
    description: 'Simple timber housing. Increases max population capacity.',
  },
  farm_plot: {
    name: 'Farm Plot',
    tier: 1,
    w: 3, h: 3,
    buildTime: 20,
    hp: 60,
    staffSlots: 1,
    description: 'Tilled earth for growing crops. Produces food over time when staffed.',
  },
  lumber_camp: {
    name: 'Lumber Camp',
    tier: 1,
    w: 2, h: 2,
    buildTime: 35,
    hp: 80,
    staffSlots: 1,
    description: 'Workers fell nearby trees for wood. Produces timber passively.',
  },
  pit_mine: {
    name: 'Pit Mine',
    tier: 1,
    w: 2, h: 3,
    buildTime: 50,
    hp: 120,
    staffSlots: 1,
    description: 'A crude dig into the earth. Produces stone and small amounts of ore.',
  },
  root_cellar: {
    name: 'Root Cellar',
    tier: 1,
    w: 2, h: 2,
    buildTime: 25,
    hp: 80,
    staffSlots: 0,
    description: 'Underground food store. Increases food storage capacity.',
  },
  herbalist: {
    name: 'Herbalist',
    tier: 1,
    w: 2, h: 2,
    buildTime: 40,
    hp: 70,
    staffSlots: 1,
    description: 'A healer who tends the sick using plants and remedies. Slowly restores citizen HP.',
  },
  palisade: {
    name: 'Palisade',
    tier: 1,
    w: 1, h: 1,
    buildTime: 8,
    hp: 60,
    staffSlots: 0,
    description: 'Sharpened wooden stakes. Basic wall section, cheap and quick to build.',
  },
  wooden_gate: {
    name: 'Wooden Gate',
    tier: 1,
    w: 1, h: 1,
    buildTime: 12,
    hp: 70,
    staffSlots: 0,
    description: 'A timber gate through your palisade. Citizens and units pass freely; enemies do not.',
  },
  watchtower: {
    name: 'Watchtower',
    tier: 1,
    w: 1, h: 2,
    buildTime: 20,
    hp: 80,
    staffSlots: 1,
    description: 'A raised wooden platform. Extends your visible map radius around it.',
  },
  arrow_tower: {
    name: 'Arrow Tower',
    tier: 1,
    w: 2, h: 2,
    buildTime: 40,
    hp: 120,
    staffSlots: 0,
    description: 'A manned wooden tower. Attacks nearby enemies automatically.',
  },

  // ── Tier 2 — The Town ────────────────────────────────────
  // Gate: completed settlement_hall + forge
  town_hall: {
    name: 'Town Hall',
    tier: 2,
    w: 4, h: 4,
    buildTime: 90,
    hp: 400,
    staffSlots: 0,
    description: 'Formalises your settlement into a town. Unlocks all Tier 2 buildings. Spawns 5 citizens.',
  },
  townhouse: {
    name: 'Townhouse',
    tier: 2,
    w: 2, h: 2,
    buildTime: 45,
    hp: 120,
    staffSlots: 0,
    description: 'A proper stone-walled home. Houses more citizens than a Log Cabin.',
  },
  forge: {
    name: 'Forge',
    tier: 2,
    w: 2, h: 2,
    buildTime: 60,
    hp: 150,
    staffSlots: 1,
    description: 'Smelts ore into metal. Required for all Tier 2 construction. Produces iron ingots.',
  },
  sawmill: {
    name: 'Sawmill',
    tier: 2,
    w: 2, h: 2,
    buildTime: 50,
    hp: 110,
    staffSlots: 1,
    description: 'Mechanised timber processing. Produces more wood than a Lumber Camp.',
  },
  quarry: {
    name: 'Quarry',
    tier: 2,
    w: 3, h: 3,
    buildTime: 70,
    hp: 160,
    staffSlots: 1,
    description: 'A proper cut-stone operation. Produces stone faster than a Pit Mine.',
  },
  granary: {
    name: 'Granary',
    tier: 2,
    w: 2, h: 2,
    buildTime: 40,
    hp: 100,
    staffSlots: 0,
    description: 'A large grain store. Significantly increases food storage and slows spoilage.',
  },
  market: {
    name: 'Market',
    tier: 2,
    w: 3, h: 2,
    buildTime: 60,
    hp: 100,
    staffSlots: 1,
    description: 'A trading hub. Generates gold income based on population size.',
  },
  blacksmith: {
    name: 'Blacksmith',
    tier: 2,
    w: 2, h: 2,
    buildTime: 60,
    hp: 130,
    staffSlots: 1,
    description: 'Forges weapons and tools. Required for the Barracks and Archery Range.',
  },
  tavern: {
    name: 'Tavern',
    tier: 2,
    w: 2, h: 2,
    buildTime: 55,
    hp: 100,
    staffSlots: 1,
    description: 'A warm place to drink and rest. Boosts citizen morale and recovery speed.',
  },
  church: {
    name: 'Church',
    tier: 2,
    w: 3, h: 3,
    buildTime: 80,
    hp: 150,
    staffSlots: 1,
    description: 'A place of worship for your people. Increases morale and reduces unrest.',
  },
  barracks: {
    name: 'Barracks',
    tier: 2,
    w: 3, h: 2,
    buildTime: 80,
    hp: 180,
    staffSlots: 4,
    description: 'Converts willing citizens into Soldiers — trained melee fighters who defend the settlement. Citizens assigned here lose their civilian role permanently and become units.',
  },
  archery_range: {
    name: 'Archery Range',
    tier: 2,
    w: 3, h: 2,
    buildTime: 75,
    hp: 150,
    staffSlots: 4,
    description: 'Trains citizens as Archers — ranged units who attack enemies from a distance. Requires a Blacksmith. Citizens assigned here become archers permanently.',
  },
  storehouse: {
    name: 'Storehouse',
    tier: 2,
    w: 3, h: 2,
    buildTime: 50,
    hp: 120,
    staffSlots: 0,
    description: 'General-purpose storage for all resources. Increases overall carrying capacity.',
  },
  stone_wall: {
    name: 'Stone Wall',
    tier: 2,
    w: 1, h: 1,
    buildTime: 20,
    hp: 200,
    staffSlots: 0,
    description: 'Mortared stone wall sections. Much stronger than palisade, harder to breach.',
  },
  ballista_tower: {
    name: 'Ballista Tower',
    tier: 2,
    w: 2, h: 2,
    buildTime: 90,
    hp: 220,
    staffSlots: 0,
    description: 'A heavy crossbow siege weapon atop a stone tower. Long range, high damage.',
  },

  // ── Tier 3 — The Castle ───────────────────────────────────
  // Gate: completed town_hall + mint
  castle_keep: {
    name: 'Castle Keep',
    tier: 3,
    w: 5, h: 5,
    buildTime: 180,
    hp: 1200,
    staffSlots: 0,
    description: 'The noble stronghold at the heart of your castle. Spawns 8 citizens. Unlocks all Tier 3 buildings.',
  },
  manor: {
    name: 'Manor',
    tier: 3,
    w: 3, h: 3,
    buildTime: 120,
    hp: 250,
    staffSlots: 0,
    description: 'Grand stone residence for your nobles and senior citizens. High capacity housing.',
  },
  mint: {
    name: 'Mint',
    tier: 3,
    w: 2, h: 2,
    buildTime: 80,
    hp: 150,
    staffSlots: 1,
    description: 'Coins raw gold into currency. Required for all Tier 3 construction. Generates wealth passively.',
  },
  cathedral: {
    name: 'Cathedral',
    tier: 3,
    w: 4, h: 5,
    buildTime: 200,
    hp: 400,
    staffSlots: 2,
    description: 'A towering place of faith. Greatly boosts morale across the entire settlement. Prestige building.',
  },
  armory: {
    name: 'Armory',
    tier: 3,
    w: 3, h: 2,
    buildTime: 100,
    hp: 200,
    staffSlots: 1,
    description: 'Stores and distributes arms and armour to your soldiers and archers. Increases unit effectiveness.',
  },
  treasury: {
    name: 'Treasury',
    tier: 3,
    w: 2, h: 2,
    buildTime: 90,
    hp: 300,
    staffSlots: 1,
    description: 'Secure vault for gold and valuables. Increases gold storage and generates small passive income.',
  },
  fortress_wall: {
    name: 'Fortress Wall',
    tier: 3,
    w: 1, h: 1,
    buildTime: 35,
    hp: 500,
    staffSlots: 0,
    description: 'Thick battlemented stone walls. The strongest wall type — very hard to destroy.',
  },
  gatehouse: {
    name: 'Gatehouse',
    tier: 3,
    w: 2, h: 2,
    buildTime: 110,
    hp: 400,
    staffSlots: 2,
    description: 'A fortified tower-flanked entrance. Stronger than a gate, can be garrisoned with soldiers.',
  },
  cannon_tower: {
    name: 'Cannon Tower',
    tier: 3,
    w: 3, h: 3,
    buildTime: 150,
    hp: 350,
    staffSlots: 0,
    description: 'A heavy artillery emplacement. Devastating range and damage, slow fire rate. Tier 3 only.',
  },
};
